### ISSUE TITLE
Not able to compile rubeus after obfuscation

### ISSUE THREAD

**Issue by G0ne** [Accenture/Codecepticon#4]
VS version: 2022 CE

Command line: .\Codecepticon.exe --action obfuscate --module csharp --verbose --path "C:\path\to\Tools\Rubeus\Rubeus.sln" --map-file "C:\path\to\Tools\Rubeus\Obfuscated-Mapping.html" --precompile --profile rubeus --rename ncefpav --rename-method markov --markov-min-length 3 --markov-max-length 9 --markov-min-words 3 --markov-max-words 4 --string-rewrite --string-rewrite-method xor

When I try to compile rubeus, this is the error I get:

Error	CS0103	The name 'ConfidenceFactor' does not exist in the current context	Rubeus	C:\path\to \Rubeus\Rubeus\lib\math\PrimeGeneratorBase.cs	18

![image](https://github.com/Accenture/Codecepticon/assets/87523421/109c65ce-0615-4002-84c9-cfb18bfbb35b)

ps: compiling rubeus without obfuscation works fine

**Comment by sadreck** [comment]
Hi,

It appears that you are trying to compile the solution under `Debug` mode. When Codecepticon opens a project for obfuscation it does so by setting it to `Release` mode, therefore it will miss those IDE conditional statements.

I've just tested your command with the latest & greatest version and compiling under `Release` worked.

Thanks,
Pavel

**Comment by G0ne** [comment]
Thanks, i compiled it! But if I try to run the .exe generated nothing happens

**Comment by G0ne** [comment]
nvm! it works fine, my bad
