### ISSUE TITLE
Seems to compile fine but get error "Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json.."

### ISSUE THREAD

**Issue by SmoothSailingMusic** [Accenture/Codecepticon#8]
Howdy.
Been trying to get this to compile but continually run into this error

C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\obj\x64\Release\net472>codecepticon.exe

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
   at Codecepticon.Program.<Main>d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Codecepticon.Program.Main(String[] args)
   at Codecepticon.Program.<Main>(String[] args)
 
Here's all the build output I have

Build started at 7:13 PM...
1>------ Build started: Project: Codecepticon, Configuration: Release x64 ------
1>Skipping analyzers to speed up the build. You can execute 'Build' or 'Rebuild' command to run analyzers.
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Modules\VB6\ANTLR\VisualBasic6BaseListener.cs(37,22,37,46): warning CS3021: 'VisualBasic6BaseListener' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Modules\VB6\ANTLR\VisualBasic6BaseVisitor.cs(36,22,36,45): warning CS3021: 'VisualBasic6BaseVisitor<Result>' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Modules\VB6\ANTLR\VisualBasic6Lexer.cs(32,22,32,39): warning CS3021: 'VisualBasic6Lexer' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Modules\VB6\ANTLR\VisualBasic6Listener.cs(32,18,32,39): warning CS3021: 'IVisualBasic6Listener' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Modules\VB6\ANTLR\VisualBasic6Parser.cs(35,22,35,40): warning CS3021: 'VisualBasic6Parser' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Modules\VB6\ANTLR\VisualBasic6Visitor.cs(33,18,33,38): warning CS3021: 'IVisualBasic6Visitor<Result>' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Modules\VB6\Vb6Manager.cs(140,34,140,51): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Modules\VB6\Vb6Manager.cs(173,34,173,39): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Modules\ModuleManager.cs(12,45,12,57): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Modules\Sign\CertificateManager.cs(56,30,56,31): warning CS0168: The variable 'e' is declared but never used
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Modules\CSharp\CSharpManager.cs(173,34,173,39): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Modules\VB6\DataRenamer.cs(20,56,20,73): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Modules\VB6\DataRenamer.cs(28,56,28,70): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Modules\VB6\DataRenamer.cs(36,56,36,75): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Modules\PowerShell\DataRenamer.cs(22,35,22,48): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Modules\PowerShell\DataCollector.cs(41,34,41,50): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Modules\PowerShell\DataRenamer.cs(50,35,50,58): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Modules\PowerShell\DataCollector.cs(60,34,60,50): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Modules\PowerShell\DataCollector.cs(77,34,77,51): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Modules\PowerShell\DataRenamer.cs(79,35,79,41): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Modules\Sign\CommandLine\ValidateCommandLine.cs(50,42,50,44): warning CS0168: The variable 'ex' is declared but never used
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Modules\PowerShell\PowerShellManager.cs(189,34,189,39): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Modules\Sign\SignManager.cs(16,27,16,30): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Modules\CSharp\DataRewriter.cs(68,37,68,57): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Modules\CSharp\Profiles\BaseProfile.cs(17,45,17,51): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Modules\CSharp\Profiles\SharpView\SharpView.cs(31,46,31,51): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Modules\CSharp\Profiles\Certify\Certify.cs(37,46,37,51): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Modules\CSharp\Profiles\Rubeus\Rubeus.cs(32,46,32,51): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Modules\CSharp\Profiles\SharpDPAPI\SharpDPAPI.cs(31,46,31,51): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Modules\CSharp\DataCollector.cs(326,34,326,53): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Modules\CSharp\Profiles\SharpHound\SharpHound.cs(72,46,72,51): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Modules\CSharp\Profiles\BaseProfile.cs(23,45,23,50): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Modules\Sign\CommandLine\SignCommandLine.cs(55,42,55,43): warning CS0168: The variable 'e' is declared but never used
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Modules\Sign\CommandLine\SignCommandLine.cs(65,42,65,43): warning CS0168: The variable 'e' is declared but never used
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Modules\CSharp\Profiles\BaseProfile.cs(48,45,48,50): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Modules\CSharp\Profiles\SharpChrome\SharpChrome.cs(32,46,32,51): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Modules\CommandLineData.cs(177,27,177,37): warning CS0649: Field 'CommandLineData.GlobalSettings.ConfigFile' is never assigned to, and will always have its default value null
1>Codecepticon -> C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\bin\x64\Release\net472\Codecepticon.exe
1>        1 file(s) copied.
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Help\CSharp.txt
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Help\Global.txt
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Help\Header.txt
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Help\PowerShell.txt
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Help\Shared.txt
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Help\Sign.txt
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Help\VBA.txt
1>7 File(s) copied
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Templates\Base64.vb6
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Templates\ExternalFile.cs
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Templates\ExternalFile.vb6
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Templates\Group.cs
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Templates\Group.ps1
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Templates\Group.vb6
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Templates\Mapping.html
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Templates\markov-english-words.txt
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Templates\Single.cs
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Templates\Single.ps1
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Templates\Single.vb6
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Templates\XOR.cs
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Templates\XOR.ps1
1>C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\Templates\XOR.vb6
1>14 File(s) copied
1>Done building project "Codecepticon.csproj".
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Build completed at 7:13 PM and took 05.830 seconds ==========
`

Any help would be appreciated as I'm an OSEP student and would love to try this tool out! 
Let me know if there is anything else you need from me.
Also can confirm I have the roslyn compiler installed.

![image](https://github.com/Accenture/Codecepticon/assets/51094038/a772471f-2b33-4f4c-b977-fb600fa40c4b)

**Comment by sadreck** [comment]
After compilation within the `Release` folder, it should look something like this:

![image](https://github.com/Accenture/Codecepticon/assets/3439227/1824d3f1-bab9-45e6-8eb3-f7259b2ab2e6)

Can you see the file there?

**Comment by SmoothSailingMusic** [comment]
Nope only got this in the release folder 
![image](https://github.com/Accenture/Codecepticon/assets/51094038/d94795ea-efc4-492f-be8b-0f9afedfe351)

**Comment by sadreck** [comment]
I noticed you're looking within the `obj` folder. Can you look inside the `bin` as that's where the compiled files are?

> C:\Tools\Codecepticon-main\Codecepticon-main\Codecepticon\bin\x64\Release\net472\Codecepticon.exe

**Comment by SmoothSailingMusic** [comment]
.... I'm an idiot. thank you. works. free to close.
